services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data:/data
      - caddy_config:/config
    networks:
      - edge

networks:
  edge:
    external: true
    name: ${EDGE_NETWORK}

volumes:
  caddy_config:
