services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
  radarr:
    image: lscr.io/linuxserver/radarr:latest
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
